### ISSUE TITLE
Update font face compatibility rule

### ISSUE THREAD

**Issue by dlburge** [SonarCommunity/sonar-css#137]
The "Font face should be made compatible with IE 6, 7 and 8" rule doesn't seem to be up-to-date with the latest best practice.

The fix: 
 - http://nemo.sonarqube.org/coding_rules#rule_key=css%3Abulletproof-font-face

should have two src attributes as shown here:
- https://css-tricks.com/snippets/css/using-font-face/

**Comment by racodond** [comment]
Indeed. That's why this rule is now deprecated. `"@font-face" rule should be made compatible with the required browsers` should be used instead. See https://github.com/SonarCommunity/sonar-css/pull/132. This new rule is part of version 1.5 that is currently undergoing contributors approval and that should be released by the end of the week. See https://groups.google.com/d/msg/sonarqube/zMiSUj2SBws/Id4FfxU0AQAJ to give it a try and provide some feedback.

**Comment by dlburge** [comment]
Ok thanks.
